DROP DATABASE IF EXISTS entradas;
CREATE DATABASE IF NOT EXISTS entradas CHARSET utf8mb4 COLLATE utf8mb4_spanish_ci;
USE entradas;

CREATE TABLE lugar (
cod_lugar INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
descripción VARCHAR(100) NOT NULL,
aforo INT NOT NULL CHECK(aforo<2000),
via VARCHAR(50) NOT NULL,
nombre VARCHAR(30) NOT NULL,
num INT(4) NOT NULL,
cod_postal VARCHAR(10) NOT NULL,
localidad VARCHAR(20) NOT NULL
) engine = innodb;

CREATE TABLE promotor(
cif VARCHAR(50) PRIMARY KEY,
razon_social VARCHAR(50) NOT NULL,
tipo VARCHAR(30) NOT NULL,
email VARCHAR(40) NOT NULL,
telf1 VARCHAR(13) NOT NULL,
telf2 VARCHAR(13)
) engine = innodb;

CREATE TABLE festival(
cod_festival INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
fecha_ini DATETIME NOT NULL,
fecha_fin DATETIME NOT NULL
) engine = innodb;

CREATE TABLE evento(
cod_evento INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
fecha DATE NOT NULL,
hora TIME NOT NULL,
cod_lugar INT UNSIGNED NOT NULL,
cif VARCHAR(50)NOT NULL,
cod_festival INT UNSIGNED,
FOREIGN KEY (cod_lugar) REFERENCES lugar(cod_lugar) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (cif) REFERENCES promotor(cif) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (cod_festival) REFERENCES festival(cod_festival) ON DELETE CASCADE ON UPDATE CASCADE
) engine = innodb;

CREATE TABLE tarifa(
cod_entrada INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
precio DECIMAL(6,2) NOT NULL,
zona VARCHAR(70) NOT NULL,
cod_evento INT UNSIGNED NOT NULL,
FOREIGN KEY (cod_evento) REFERENCES evento(cod_evento) ON DELETE CASCADE ON UPDATE CASCADE
) engine = innodb;

CREATE TABLE cliente(
email VARCHAR(50) PRIMARY KEY,
dni VARCHAR(9) UNIQUE NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellidos VARCHAR(50) NOT NULL,
telf1 VARCHAR(13) NOT NULL,
telf2 VARCHAR(13)
) engine = innodb;

CREATE TABLE entrada(
Cod_entrada INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Localidad VARCHAR(50) NOT NULL,
Zona VARCHAR(50) NOT NULL,
Cod_evento INT UNSIGNED NOT NULL,
Email VARCHAR(50) NOT NULL,
Medio_pago VARCHAR(50) NOT NULL,
Fecha_compra DATETIME NOT NULL,
Precio DECIMAL(6,2) NOT NULL,
FOREIGN KEY (cod_evento) REFERENCES evento(cod_evento) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (email) REFERENCES cliente(email) ON DELETE CASCADE ON UPDATE CASCADE
) engine = innodb;